# CRT Trading Bot - NinjaTrader bridge setup (Windows)
Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass -Force
$ErrorActionPreference = "Stop"
$RepoRoot = Split-Path -Parent $PSScriptRoot
$SourceCs = Join-Path $RepoRoot "phase74\market_data\ninjatrader\CRTBarBridge.cs"
$TokenFileName = "crt_bridge_token.txt"

function Find-NinjaTraderIndicatorsDirs {
    $dirs = @()
    $candidates = @(
        (Join-Path $env:USERPROFILE "OneDrive\Documents\NinjaTrader 8\bin\Custom\Indicators"),
        (Join-Path $env:USERPROFILE "Documents\NinjaTrader 8\bin\Custom\Indicators")
    )
    foreach ($path in $candidates) {
        $customRoot = Split-Path (Split-Path $path -Parent) -Parent
        if (Test-Path $customRoot) {
            New-Item -ItemType Directory -Force -Path $path | Out-Null
            if ($dirs -notcontains $path) { $dirs += $path }
        }
    }
    return $dirs
}

function Find-NinjaTraderCustomDirs {
    $dirs = @()
    foreach ($ind in (Find-NinjaTraderIndicatorsDirs)) {
        $custom = Split-Path (Split-Path $ind -Parent) -Parent
        if ($dirs -notcontains $custom) { $dirs += $custom }
    }
    return $dirs
}

function New-RandomToken {
    param([int]$Length = 48)
    $chars = (48..57) + (65..90) + (97..122) | ForEach-Object { [char]$_ }
    -join (1..$Length | ForEach-Object { $chars | Get-Random })
}

function Sync-BridgeTokenFile {
    param([string]$Token, [string]$CustomDir)
    $tokenPath = Join-Path $CustomDir $TokenFileName
    Set-Content -Path $tokenPath -Value $Token -Encoding ASCII -NoNewline
    Write-Host "Token file: $tokenPath" -ForegroundColor Green
}

Write-Host "`n=== CRT NinjaTrader Bridge Setup ===" -ForegroundColor Cyan

$ntIndDirs = Find-NinjaTraderIndicatorsDirs
if (-not $ntIndDirs -or $ntIndDirs.Count -eq 0) {
    Write-Host "NinjaTrader Custom folder not found. Install NT8 first, then re-run." -ForegroundColor Red
    exit 1
}

# Install to ONE Indicators folder only — duplicate copies cause CS0111/CS0121 on compile.
$ntInd = $ntIndDirs[0]
foreach ($extra in $ntIndDirs | Select-Object -Skip 1) {
    $dup = Join-Path $extra "CRTBarBridge.cs"
    if (Test-Path $dup) {
        Remove-Item -Force $dup
        Write-Host "Removed duplicate: $dup" -ForegroundColor Yellow
    }
}
Copy-Item -Force $SourceCs (Join-Path $ntInd "CRTBarBridge.cs")
Write-Host "Installed: $(Join-Path $ntInd 'CRTBarBridge.cs')" -ForegroundColor Green

$envFile = Join-Path $RepoRoot "phase74\.env"
$bridgeToken = $null
$webhookSecret = $null
if (Test-Path $envFile) {
    Get-Content $envFile | ForEach-Object {
        if ($_ -match '^\s*NINJATRADER_BRIDGE_TOKEN=(.+)$') { $bridgeToken = $Matches[1].Trim() }
        if ($_ -match '^\s*PHASE74_WEBHOOK_SECRET=(.+)$') { $webhookSecret = $Matches[1].Trim() }
    }
}
if (-not $bridgeToken) { $bridgeToken = New-RandomToken }
if (-not $webhookSecret) { $webhookSecret = New-RandomToken }

@"
# Generated by scripts/setup-ninjatrader-bridge.ps1 - never commit
TRADING_ENABLED=false
SHADOW_MODE=true
EXTERNAL_ORDER_ROUTING=false
NINJATRADER_BRIDGE_TOKEN=$bridgeToken
NINJATRADER_BRIDGE_TRUST_LOCALHOST=true
PHASE74_WEBHOOK_SECRET=$webhookSecret
PHASE74_KILL_SWITCH=0
"@ | Set-Content -Path $envFile -Encoding UTF8

$customDir = Split-Path (Split-Path $ntInd -Parent) -Parent
Sync-BridgeTokenFile -Token $bridgeToken -CustomDir $customDir

Write-Host "Wrote secrets: phase74\.env" -ForegroundColor Green
Write-Host "Auth token synced to crt_bridge_token.txt (CRTBarBridge reads this when AuthToken is blank)." -ForegroundColor Green
Write-Host "Webhook token for TV alerts: $webhookSecret" -ForegroundColor Yellow
Write-Host "Public webhook (ngrok): https://finale-streak-bucket.ngrok-free.dev/webhook?token=$webhookSecret" -ForegroundColor Yellow

Get-Content $envFile | ForEach-Object {
    if ($_ -match '^\s*([^#=]+)=(.*)$') {
        [System.Environment]::SetEnvironmentVariable($Matches[1].Trim(), $Matches[2].Trim(), 'Process')
    }
}

Write-Host "`n=== NinjaTrader (one-time if indicator not on chart) ===" -ForegroundColor Cyan
Write-Host "1. NT should auto-recompile when CRTBarBridge.cs changes (NinjaScript Editor open helps)."
Write-Host "2. Chart: NQ 1-minute, timezone UTC, indicator CRTBarBridge (AuthToken can stay blank)."
Write-Host "3. Start Python BEFORE enabling the chart indicator."
Write-Host "`nStart stack: .\scripts\start-ninjatrader-shadow.ps1" -ForegroundColor Green
