# CRT Trading Bot — NinjaTrader bridge setup (Windows)
Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass -Force
$ErrorActionPreference = "Stop"
$RepoRoot = Split-Path -Parent $PSScriptRoot
$SourceCs = Join-Path $RepoRoot "phase74\market_data\ninjatrader\CRTBarBridge.cs"

function Find-NinjaTraderIndicatorsDir {
    $candidates = @(
        (Join-Path $env:USERPROFILE "OneDrive\Documents\NinjaTrader 8\bin\Custom\Indicators"),
        (Join-Path $env:USERPROFILE "Documents\NinjaTrader 8\bin\Custom\Indicators")
    )
    foreach ($path in $candidates) {
        if (Test-Path (Split-Path $path -Parent)) {
            New-Item -ItemType Directory -Force -Path $path | Out-Null
            return $path
        }
    }
    return $null
}

function New-RandomToken {
    param([int]$Length = 48)
    $chars = (48..57) + (65..90) + (97..122) | ForEach-Object { [char]$_ }
    -join (1..$Length | ForEach-Object { $chars | Get-Random })
}

Write-Host "`n=== CRT NinjaTrader Bridge Setup ===" -ForegroundColor Cyan

# 1) Install indicator
$ntInd = Find-NinjaTraderIndicatorsDir
if (-not $ntInd) {
    Write-Host "NinjaTrader Custom folder not found. Install NT8 first, then re-run." -ForegroundColor Red
    exit 1
}
Copy-Item -Force $SourceCs (Join-Path $ntInd "CRTBarBridge.cs")
Write-Host "Installed: $(Join-Path $ntInd 'CRTBarBridge.cs')" -ForegroundColor Green

# 2) Create/update phase74/.env (gitignored)
$envFile = Join-Path $RepoRoot "phase74\.env"
$bridgeToken = New-RandomToken
$webhookSecret = $null
if (Test-Path $envFile) {
    $existing = Get-Content $envFile -Raw
    if ($existing -match '(?m)^PHASE74_WEBHOOK_SECRET=(.+)$') {
        $webhookSecret = $Matches[1].Trim()
    }
}
if (-not $webhookSecret) {
    $webhookSecret = New-RandomToken
}

@"
# Generated by scripts/setup-ninjatrader-bridge.ps1 — never commit
TRADING_ENABLED=false
SHADOW_MODE=true
EXTERNAL_ORDER_ROUTING=false
NINJATRADER_BRIDGE_TOKEN=$bridgeToken
PHASE74_WEBHOOK_SECRET=$webhookSecret
PHASE74_KILL_SWITCH=0
"@ | Set-Content -Path $envFile -Encoding UTF8

Write-Host "Wrote secrets: phase74\.env" -ForegroundColor Green
Write-Host "`n--- COPY THIS AuthToken INTO NINJATRADER CRTBarBridge ---"
Write-Host $bridgeToken -ForegroundColor Yellow
Write-Host "`n--- Webhook token (for TV alert URL) ---"
Write-Host $webhookSecret -ForegroundColor Yellow

# 3) Load .env for current session
Get-Content $envFile | ForEach-Object {
    if ($_ -match '^\s*([^#=]+)=(.*)$') {
        [System.Environment]::SetEnvironmentVariable($Matches[1].Trim(), $Matches[2].Trim(), 'Process')
    }
}

Write-Host "`n=== YOU MUST DO IN NINJATRADER (GUI) ===" -ForegroundColor Cyan
Write-Host "1. Control Center -> New -> NinjaScript Editor"
Write-Host "2. Right-click Indicators -> Compile (expect 0 errors)"
Write-Host "3. New Chart: NQ, 1 Minute, timezone UTC"
Write-Host "4. Add indicator CRTBarBridge"
Write-Host "   Host=127.0.0.1  Port=8765  AuthToken=<token above>"
Write-Host "5. Start Python FIRST, then enable/reload the chart indicator"
Write-Host "`nTo start Python bot:"
Write-Host "  .\scripts\start-ninjatrader-shadow.ps1" -ForegroundColor Green
